create table public.recipes (
  id bigint generated by default as identity primary key,
  recipe jsonb not null,
  image_path text,
  external_image text,
  version integer not null default 1,
  created_at timestamptz not null default now()
);
alter table public.recipes enable row level security;
revoke all on public.recipes from anon, authenticated;
grant all on public.recipes to service_role;
grant usage, select on sequence public.recipes_id_seq to service_role;

create table public.recipe_login_limits (
  key text primary key,
  started_at timestamptz not null default now(),
  attempts integer not null default 1
);
alter table public.recipe_login_limits enable row level security;
revoke all on public.recipe_login_limits from anon, authenticated;

create function public.recipe_login_allowed(limit_key text)
returns boolean language plpgsql security definer set search_path = '' as $$
declare attempt_count integer;
begin
  delete from public.recipe_login_limits where started_at < now() - interval '1 day';
  insert into public.recipe_login_limits as limits (key) values (limit_key)
  on conflict (key) do update set
    attempts = case when limits.started_at < now() - interval '15 minutes' then 1 else limits.attempts + 1 end,
    started_at = case when limits.started_at < now() - interval '15 minutes' then now() else limits.started_at end
  returning attempts into attempt_count;
  return attempt_count <= 15;
end;
$$;
revoke all on function public.recipe_login_allowed(text) from public, anon, authenticated;
grant execute on function public.recipe_login_allowed(text) to service_role;

create function public.import_recipe_backup(items jsonb)
returns integer language plpgsql security definer set search_path = '' as $$
declare imported integer;
begin
  lock table public.recipes in exclusive mode;
  insert into public.recipes (id, recipe, external_image)
  select (item->>'id')::bigint, item - 'id' - 'image', nullif(item->>'image', '')
  from jsonb_array_elements(items) item
  on conflict (id) do nothing;
  get diagnostics imported = row_count;
  perform setval(pg_get_serial_sequence('public.recipes', 'id'), coalesce((select max(id) from public.recipes), 1), exists(select 1 from public.recipes));
  return imported;
end;
$$;
revoke all on function public.import_recipe_backup(jsonb) from public, anon, authenticated;
grant execute on function public.import_recipe_backup(jsonb) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('recipe-images', 'recipe-images', false, 6291456, array['image/jpeg', 'image/png', 'image/webp']);
-- No anonymous or authenticated-user policies: all access is through the password-checked function.
